version: 0.1

env:
  shell: bash
  variables:
    NODE_ENV: production
  exported-variables:
    - NODE_ENV

phases:
  install:
    commands:
      - npm install -g lerna
  pre_build:
    commands:
      - lerna bootstrap --no-ci --concurrency 4
  build:
    commands:
      - yarn --cwd=packages/styles build
      - yarn --cwd=packages/react build
      # - lerna run build --concurrency 4
  post_build:
    commands:
      - yarn --cwd=packages/react test
      - yarn dev &
      - sleep 5 && yarn test-pa11y-axe
      - yarn generate-pa11y-axe-report
      - yarn print-pa11y-axe-cli-results
artifacts:
  files:
    - "docs/dist/*"
