# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [10.x, 12.x, 14.x]
        node-version: [10.x]

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache yarn modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: v1-yarn-deps-${{ hashFiles('yarn.lock') }}
        restore-keys: v1-yarn-deps-

    - name: Cache react modules
      uses: actions/cache@v2
      with:
        path: packages/react/node_modules
        key: v1-react-deps-${{ hashFiles('packages/react/yarn.lock') }}
        restore-keys: v1-react-deps-

    - name: Cache styles modules
      uses: actions/cache@v2
      with:
        path: packages/styles/node_modules
        key: v1-styles-deps-${{ hashFiles('packages/styles/yarn.lock') }}
        restore-keys: v1-styles-deps-

    - run: yarn
    - run: npx lerna bootstrap
    - run: NODE_ENV=production yarn --cwd=packages/styles build
    - run: NODE_ENV=production yarn --cwd=packages/react build
    - run: yarn --cwd=packages/react test
    - run: yarn dev &
    - run: sleep 20 && yarn test-pa11y
    - run: yarn build

    - name: Upload Website
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: 'docs/dist'
